"use strict";
const pageSuffix = "/agent-runtime";
const prefix = location.pathname.endsWith(pageSuffix) ? location.pathname.slice(0, -pageSuffix.length) : "";
const API = `${prefix}/api/local/agent-runtime`;
const $ = (value) => document.querySelector(value);
const state = { providers: [], models: [], agents: [], sessions: [], session: null, controller: null };
let noticeTimer;

function notice(text, error = false) { clearTimeout(noticeTimer); const node = $("#notice"); node.textContent = text; node.className = error ? "error" : ""; node.hidden = false; noticeTimer = setTimeout(() => { node.hidden = true; }, 6500); }
async function api(path, options = {}) { const response = await fetch(`${API}${path}`, options); if (!response.ok) { let body = {}; try { body = await response.json(); } catch {} throw new Error(body?.error?.message || `请求失败 (${response.status})`); } return response.json(); }
function post(path, body, accept = "application/json") { return fetch(`${API}${path}`, { method: "POST", headers: { "Content-Type": "application/json", Accept: accept, "Idempotency-Key": crypto.randomUUID() }, body: JSON.stringify(body) }); }
function profile(primary, detail, stateText = "") { const item = document.createElement("article"); item.className = "profile"; const strong = document.createElement("strong"); strong.textContent = primary; const small = document.createElement("small"); small.textContent = detail; item.append(strong, small); if (stateText) { const status = document.createElement("span"); status.textContent = stateText; item.append(status); } return item; }
function option(select, value, text) { const node = document.createElement("option"); node.value = value; node.textContent = text; select.append(node); }
function bindSelect(selector, rows, label) { const select = $(selector); const prior = select.value; select.replaceChildren(); option(select, "", rows.length ? "请选择" : "请先完成上游配置"); rows.filter((row) => row.enabled).forEach((row) => option(select, row.id, row[label])); select.value = [...select.options].some((row) => row.value === prior) ? prior : ""; select.disabled = !rows.some((row) => row.enabled); }
function runtimeView(runtime) { const enabled = runtime.runtime_enabled; $("#runtime-badge").textContent = enabled ? "● RUNTIME GATE ENABLED" : "● EXTERNAL MODEL DISABLED"; $("#runtime-badge").className = enabled ? "enabled" : "blocked"; $("#runtime").textContent = `${runtime.note} 当前统计：模型 ${runtime.model_calls}、Provider ${runtime.provider_calls}、网络 ${runtime.network_calls}、工具绑定 ${runtime.tool_binding_count}。`; }
async function renderProfiles() { const providers = $("#provider-list"); providers.replaceChildren(); for (const row of state.providers) { const ready = await api(`/providers/${encodeURIComponent(row.id)}/readiness`); providers.append(profile(row.name, `${row.type} · ${row.base_url}`, ready.state)); } if (!state.providers.length) providers.append(profile("尚无 Provider", "先建立无密连接描述")); const models = $("#model-list"); models.replaceChildren(); state.models.forEach((row) => models.append(profile(row.display_name, `${row.model_id} · ${row.context_window.toLocaleString()} tokens`))); if (!state.models.length) models.append(profile("尚无 Model", "Provider 建立后可配置")); const agents = $("#agent-list"); agents.replaceChildren(); state.agents.forEach((row) => agents.append(profile(row.name, `${row.max_context_turns} 轮上下文 · 工具绑定 ${row.tool_binding_count}`))); if (!state.agents.length) agents.append(profile("尚无 Agent", "模型建立后可配置")); bindSelect("#model-provider", state.providers, "name"); bindSelect("#agent-model", state.models, "display_name"); bindSelect("#session-agent", state.agents, "name"); $("#model-form button").disabled = !state.providers.some((row) => row.enabled); $("#agent-form button").disabled = !state.models.some((row) => row.enabled); $("#new-session").disabled = !state.agents.some((row) => row.enabled); }
function renderSessions() { const target = $("#session-list"); target.replaceChildren(); state.sessions.forEach((row) => { const button = document.createElement("button"); button.type = "button"; button.dataset.session = row.id; button.className = state.session?.id === row.id ? "selected" : ""; const name = document.createElement("strong"); name.textContent = row.title; const detail = document.createElement("small"); detail.textContent = row.status === "active" ? "持久会话" : "已归档"; button.append(name, detail); target.append(button); }); if (!state.sessions.length) target.append(profile("还没有会话", "选择 Agent 后新建会话")); }
function bubble(message) { const node = document.createElement("article"); node.className = `bubble ${message.role}`; const role = document.createElement("small"); role.textContent = message.role === "user" ? "你" : "ASSISTANT"; const content = document.createElement("div"); content.textContent = message.content; node.append(role, content); return node; }
function renderMessages(messages) { const box = $("#messages"); box.replaceChildren(); messages.forEach((item) => box.append(bubble(item))); box.scrollTop = box.scrollHeight; }
async function chooseSession(id) { const detail = await api(`/sessions/${encodeURIComponent(id)}`); state.session = detail.session; renderSessions(); renderMessages(detail.messages); $("#empty").hidden = true; $("#messages").hidden = false; $("#chat-form").hidden = false; }
async function refresh() { const [providers, models, agents, sessions] = await Promise.all([api("/providers"), api("/models"), api("/agents"), api("/sessions")]); state.providers = providers.items; state.models = models.items; state.agents = agents.items; state.sessions = sessions.items; runtimeView(providers.runtime); await renderProfiles(); renderSessions(); $("#connection").textContent = "本地控制面已连接"; }
async function submitProfile(event, path) { event.preventDefault(); const form = event.currentTarget; const button = form.querySelector("button[type=submit]"); button.disabled = true; try { const body = Object.fromEntries(new FormData(form)); ["context_window", "max_output_tokens", "max_context_turns"].forEach((name) => { if (body[name]) body[name] = Number(body[name]); }); if (body.temperature) body.temperature = Number(body.temperature); if (!body.credential_ref) delete body.credential_ref; const response = await post(path, body); if (!response.ok) { const error = await response.json(); throw new Error(error?.error?.message || "保存失败"); } form.reset(); if (form.id === "provider-form") form.elements.base_url.value = "https://example.invalid"; if (form.id === "model-form") form.elements.context_window.value = "32768"; if (form.id === "agent-form") { form.elements.system_prompt.value = "你是一个审慎的研究助手。只基于可用事实回答，并明确不确定性。"; form.elements.temperature.value = "0.3"; form.elements.max_output_tokens.value = "1024"; form.elements.max_context_turns.value = "8"; } await refresh(); notice("配置已保存；没有发起外部网络连接。"); } finally { button.disabled = false; } }
function parseSse(buffer, callback) { const parts = buffer.split(/\r?\n\r?\n/); const rest = parts.pop(); parts.forEach((part) => { const line = part.split(/\r?\n/).find((value) => value.startsWith("data:")); if (line) callback(JSON.parse(line.replace(/^data:\s*/, ""))); }); return rest; }
function scrollNearBottom() { const box = $("#messages"); if (box.scrollHeight - box.scrollTop - box.clientHeight < 90) box.scrollTop = box.scrollHeight; }
async function sendMessage(event) { event.preventDefault(); if (!state.session || state.controller) return; const input = $("#chat-input"); const content = input.value.trim(); if (!content) return; const send = $("#send"), stop = $("#stop"), box = $("#messages"); input.value = ""; send.disabled = true; stop.hidden = false; box.append(bubble({ role: "user", content })); const assistant = bubble({ role: "assistant", content: "正在检查运行时门禁…" }); const target = assistant.querySelector("div"); box.append(assistant); scrollNearBottom(); state.controller = new AbortController(); try { const response = await fetch(`${API}/sessions/${encodeURIComponent(state.session.id)}/messages`, { method: "POST", signal: state.controller.signal, headers: { "Content-Type": "application/json", Accept: "text/event-stream", "Idempotency-Key": crypto.randomUUID() }, body: JSON.stringify({ content }) }); if (!response.ok || !response.body) { let body = {}; try { body = await response.json(); } catch {} throw new Error(body?.error?.message || "流式请求失败"); } target.textContent = ""; const reader = response.body.getReader(), decoder = new TextDecoder(); let buffer = "", terminal = false; while (!terminal) { const result = await reader.read(); if (result.done) break; buffer = parseSse(buffer + decoder.decode(result.value, { stream: true }), (item) => { if (item.type === "delta") { target.textContent += item.content; scrollNearBottom(); } else if (item.type === "error") { target.textContent = `系统未生成回答：${item.error_code}`; terminal = true; } else if (item.type === "done") terminal = true; }); } await chooseSession(state.session.id); notice("流式请求已结束。请以会话中的持久记录为准。"); } catch (error) { target.textContent = error.name === "AbortError" ? "浏览器已停止显示；刷新会话可查看已持久化的状态。" : `发送失败：${error.message}`; notice(error.message || "流式请求失败", true); } finally { state.controller = null; send.disabled = false; stop.hidden = true; input.focus(); } }
function guard(handler) { return async (event) => { try { await handler(event); } catch (error) { notice(error.message || "操作失败", true); } }; }
$("#provider-form").addEventListener("submit", guard((event) => submitProfile(event, "/providers"))); $("#model-form").addEventListener("submit", guard((event) => submitProfile(event, "/models"))); $("#agent-form").addEventListener("submit", guard((event) => submitProfile(event, "/agents"))); $("#new-session").addEventListener("click", guard(async () => { const agent_profile_id = $("#session-agent").value; if (!agent_profile_id) throw new Error("请先选择 Agent。"); const response = await post("/sessions", { agent_profile_id }); if (!response.ok) { const body = await response.json(); throw new Error(body?.error?.message || "创建会话失败"); } const session = await response.json(); await refresh(); await chooseSession(session.id); notice("会话已创建。"); })); $("#session-list").addEventListener("click", guard(async (event) => { const button = event.target.closest("[data-session]"); if (button) await chooseSession(button.dataset.session); })); $("#chat-form").addEventListener("submit", guard(sendMessage)); $("#stop").addEventListener("click", () => state.controller?.abort()); refresh().catch((error) => { $("#connection").textContent = "连接中断"; notice(error.message, true); });
