"use strict";
const $=id=>document.getElementById(id), url=path=>HarnessURLs.url('/api/local/support'+path);
const state={providers:[],agents:[],sessions:[],selected:null,generation:0,controller:null,exchange:null,sendingSession:null};
async function api(path,method='GET',body){const r=await fetch(url(path),{method,headers:body===undefined?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const v=await r.json();if(!r.ok)throw Error(v.error?.message+' ['+v.error?.code+']');return v;}
function status(t){$('status').textContent=t;}
function node(tag,text,cls){const n=document.createElement(tag);n.textContent=text;if(cls)n.className=cls;return n;}
function button(label,fn){const b=node('button',label);b.type='button';b.onclick=()=>Promise.resolve().then(fn).catch(e=>status(e.message));return b;}
function options(select,items,label){const old=select.value;select.replaceChildren(...items.map(i=>{const o=node('option',label(i));o.value=i.id;return o;}));if(items.some(i=>i.id===old))select.value=old;}
function selectTab(id){document.querySelectorAll('.tab').forEach(e=>e.hidden=e.id!==id);document.querySelectorAll('[data-tab]').forEach(e=>e.classList.toggle('active',e.dataset.tab===id));}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>selectTab(b.dataset.tab));
function renderProviders(){const cards=state.providers.map(p=>{const n=node('div','', 'card');n.append(node('strong',p.name),node('p',p.model),node('p',p.enabled?'已启用 · 凭证已加密':'已停用'),node('p','探测：'+p.health.state+(p.health.code?' / '+p.health.code:'')),node('p',p.health.checked_at||'尚未探测'));n.append(button('编辑',()=>{for(const [id,key] of [['id','id'],['name','name'],['url','base_url'],['model','model'],['interval','probe_interval_seconds']])$('provider-'+id).value=p[key];$('provider-key').value='';$('provider-enabled').checked=p.enabled;$('provider-auto').checked=p.auto_probe;}),button('立即探测',async()=>{status('正在探测…');const h=await api('/providers/'+p.id+'/probe','POST',{});status('探测：'+h.state+(h.code?' / '+h.code:''));await refresh();}),button('删除',async()=>{if(confirm('删除此 Provider 配置及加密凭证？')){await api('/providers/'+p.id,'DELETE');await refresh();}}));return n;});$('provider-list').replaceChildren(...cards);options($('agent-provider'),state.providers,p=>p.name+' / '+p.model);}
function renderAgents(){const cards=state.agents.map(a=>{const n=node('div','', 'card');n.append(node('strong',a.name),node('p',a.model),node('p',a.enabled?'启用':'停用'));n.append(button('编辑',()=>{for(const [id,key] of [['id','id'],['name','name'],['provider','provider_id'],['model','model'],['prompt','system_prompt'],['output','max_output_tokens'],['budget','token_budget']])$('agent-'+id).value=a[key];$('agent-enabled').checked=a.enabled;$('agent-workflow').value=a.workflow_ids[0]||'';for(const [id,key] of [["agent-knowledge","knowledge_ids"],["agent-mcp","mcp_ids"],["agent-tools","tools"]])for(const o of $(id).options)o.selected=a[key].includes(o.value);}),button('删除',async()=>{if(confirm('删除 Agent？已被会话使用时会拒绝。')){await api('/agents/'+a.id,'DELETE');await refresh();}}));return n;});$('agent-list').replaceChildren(...cards);options($('chat-agent'),state.agents.filter(a=>a.enabled),a=>a.name);}
function renderSessions(){$('sessions').replaceChildren(...state.sessions.map(s=>{const b=button(s.title,()=>selectSession(s.id));b.classList.toggle('active',s.id===state.selected);return b;}));}
function message(role,text,preview=false){const n=node('div','', 'message '+role+(preview?' preview':''));n.append(node('div',role==='user'?'你':preview?'助手 · 未提交预览':'助手','role'),node('div',text));$('messages').append(n);$('messages').scrollTop=$('messages').scrollHeight;return n.lastChild;}
async function refresh(){const [p,a,s,r]=await Promise.all([api('/providers'),api('/agents'),api('/sessions'),api('/status')]);state.providers=p.items;state.agents=a.items;state.sessions=s.items;renderProviders();renderAgents();renderSessions();$('runtime').textContent=(r.enabled?'客服已启用':'客服未启用')+' · '+(r.automatic_probes_running?'后台探测运行中':'后台探测未运行');}
async function selectSession(id){const generation=++state.generation;state.selected=id;renderSessions();$('session-title').textContent='读取会话…';$('messages').replaceChildren();const d=await api('/sessions/'+id);if(generation!==state.generation)return;$('session-title').textContent=d.session.title;for(const m of d.messages){message(m.role,m.content);if(m.role==='assistant'){const e=d.exchanges.find(e=>e.id===m.exchange_id);if(e?.sources?.length){const details=node('details','');details.append(node('summary','参考资料（来源存在不代表结论必然正确）'),node('p',e.sources.map(s=>s.name+' · '+s.score+' · '+s.ref).join('\n')));$('messages').append(details);}}}const latest=d.exchanges.at(-1);if(latest&&['failed','cancelled'].includes(latest.status))message('assistant','本轮未完成：'+latest.error_code);$('stop').disabled=!state.controller||state.sendingSession!==id;}
$('provider-form').onsubmit=async e=>{e.preventDefault();try{const id=$('provider-id').value,body={name:$('provider-name').value,base_url:$('provider-url').value,model:$('provider-model').value,enabled:$('provider-enabled').checked,auto_probe:$('provider-auto').checked,probe_interval_seconds:Number($('provider-interval').value)};if($('provider-key').value)body.api_key=$('provider-key').value;await api('/providers'+(id?'/'+id:''),id?'PUT':'POST',body);$('provider-key').value='';status('Provider 已加密保存');await refresh();}catch(e){status(e.message);}};
$('provider-reset').onclick=()=>{$('provider-form').reset();$('provider-id').value='';};
$('agent-form').onsubmit=async e=>{e.preventDefault();try{const id=$('agent-id').value,body={name:$('agent-name').value,provider_id:$('agent-provider').value,model:$('agent-model').value,system_prompt:$('agent-prompt').value,max_output_tokens:Number($('agent-output').value),token_budget:Number($('agent-budget').value),tools:[...$("agent-tools").selectedOptions].map(o=>o.value),mcp_ids:[...$("agent-mcp").selectedOptions].map(o=>o.value),knowledge_ids:[...$('agent-knowledge').selectedOptions].map(o=>o.value),workflow_ids:$('agent-workflow').value?[$('agent-workflow').value]:[],enabled:$('agent-enabled').checked};await api('/agents'+(id?'/'+id:''),id?'PUT':'POST',body);status('Agent 已保存；新配置用于新会话');await refresh();}catch(e){status(e.message);}};
$('agent-reset').onclick=()=>{$('agent-form').reset();$('agent-id').value='';};
$('new-session').onclick=async()=>{try{const a=state.agents.find(a=>a.id===$('chat-agent').value);if(!a)throw Error('请先配置 Provider 和 Agent');const s=await api('/sessions','POST',{agent_id:a.id,title:a.name+' · '+new Date().toLocaleTimeString()});await refresh();await selectSession(s.id);}catch(e){status(e.message);}};
$('stop').onclick=async()=>{if(state.sendingSession!==state.selected)return;try{if(state.exchange)await api('/exchanges/'+state.exchange+'/cancel','POST',{});}finally{state.controller?.abort();}};
$('chat-form').onsubmit=async e=>{e.preventDefault();if(state.controller)return;if(!state.selected){status('请先创建会话');return;}const session=state.selected,generation=state.generation,content=$('question').value;state.controller=new AbortController();state.sendingSession=session;state.exchange=null;$('send').disabled=true;$('stop').disabled=false;$('question').value='';message('user',content);const preview=message('assistant','',true);let terminal=false,buffer='',shown='';const current=()=>state.selected===session&&state.generation===generation;
try{const r=await fetch(url('/sessions/'+session+'/messages'),{method:'POST',signal:state.controller.signal,headers:{'Content-Type':'application/json','Accept':'text/event-stream','Idempotency-Key':HarnessURLs.requestId()},body:JSON.stringify({content})});if(!r.ok){const err=await r.json();throw Error(err.error?.message||'请求失败');}const reader=r.body.getReader(),decoder=new TextDecoder();while(true){const {value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});let p;while((p=buffer.indexOf('\n\n'))>=0){const frame=buffer.slice(0,p);buffer=buffer.slice(p+2);const data=frame.split('\n').filter(l=>l.startsWith('data: ')).map(l=>l.slice(6)).join('\n');if(!data)continue;const event=JSON.parse(data);if(event.exchange_id)state.exchange=event.exchange_id;if(event.type==='delta'){shown+=event.content;if(current())preview.textContent=shown;}if(event.type==='tool'&&current())status('工具完成：'+event.tool);if(event.type==='done'){terminal=true;if(current())status('回答已保存 · Token '+event.budget.spent);}if(event.type==='error'){terminal=true;throw Error(event.error_code);}}}if(!terminal)throw Error('连接提前结束，未确认回答成功');}
catch(e){if(current())status(e.name==='AbortError'?'已停止接收，正在核对持久状态':e.message);}
finally{state.controller=null;state.sendingSession=null;state.exchange=null;$('send').disabled=false;$('stop').disabled=true;if(current())await selectSession(session);await refresh();}};
selectTab('chat');refresh().catch(e=>status(e.message));
