"use strict";
let mcpServers=[],demoEndpoint='',debugHistory=[];
async function refreshMcp(){const result=await api('/mcp');mcpServers=result.items;demoEndpoint=result.demo_endpoint;if(!$('mcp-endpoint').value)$('mcp-endpoint').value=demoEndpoint;
options($('agent-mcp'),mcpServers.filter(s=>s.enabled),s=>s.name);
const all=mcpServers.filter(s=>s.enabled).flatMap(s=>s.tools.map(t=>({...t,id:t.alias,server:s.id,label:s.name+' / '+t.name})));
options($('agent-tools'),all,t=>t.label);options($('mcp-debug-tool'),all,t=>t.label);
$('mcp-list').replaceChildren(...mcpServers.map(s=>{const card=node('div','', 'card');card.append(node('strong',s.name),node('p',s.endpoint),node('p',(s.enabled?'启用':'停用')+' · '+s.tools.length+' 个工具'),button('发现工具',async()=>{await api('/mcp/'+s.id+'/discover','POST',{});await refreshMcp();status('工具已发现；绑定 Agent 后创建新会话');}),button('编辑',()=>{$('mcp-id').value=s.id;$('mcp-name').value=s.name;$('mcp-endpoint').value=s.endpoint;$('mcp-enabled').checked=s.enabled;$('mcp-reads').value=s.read_only_tools.join(',');}),button('删除',async()=>{if(confirm('删除此 MCP 配置？绑定的会话会停止使用它。')){await api('/mcp/'+s.id,'DELETE');await refreshMcp();}}));return card;}));}
async function refreshApprovals(){const result=await api('/approvals');$('approvals').replaceChildren(...result.items.map(a=>{const card=node('div','', 'card');card.append(node('strong',a.tool+' · '+a.status),node('p',a.id),node('pre',JSON.stringify(a.arguments,null,2)),node('p','创建：'+a.created_at+' · '+(a.context.debug?'调试请求':'会话 '+a.context.session_id)));if(a.status==='pending'){card.append(button('确认执行',async()=>{if(confirm('确认按显示的参数执行？外部工具可能产生副作用；内置退款仅修改合成记录。')){const r=await api('/approvals/'+a.id+'/decision','POST',{decision:'approve'});status('动作状态：'+r.status);await refreshApprovals();}}),button('拒绝',async()=>{await api('/approvals/'+a.id+'/decision','POST',{decision:'reject'});await refreshApprovals();}));}if(a.result)card.append(node('pre',JSON.stringify(a.result,null,2)));if(a.status==='unknown')card.append(node('p','结果未知：禁止自动重试，请先查询业务记录。'));return card;}));}
$('mcp-form').onsubmit=async e=>{e.preventDefault();try{const id=$('mcp-id').value;await api('/mcp'+(id?'/'+id:''),id?'PUT':'POST',{name:$('mcp-name').value,endpoint:$('mcp-endpoint').value,enabled:$('mcp-enabled').checked,read_only_tools:$('mcp-reads').value.split(',').map(s=>s.trim()).filter(Boolean)});await refreshMcp();status('配置已保存，请点击发现工具');}catch(e){status(e.message);}};
$('mcp-reset').onclick=()=>{$('mcp-form').reset();$('mcp-id').value='';$('mcp-endpoint').value=demoEndpoint;};
$('mcp-debug').onsubmit=async e=>{e.preventDefault();try{const alias=$('mcp-debug-tool').value,s=mcpServers.find(s=>s.tools.some(t=>t.alias===alias)),t=s?.tools.find(t=>t.alias===alias);if(!t)throw Error('请先发现工具');const result=await api('/mcp/'+s.id+'/debug','POST',{name:t.name,arguments:JSON.parse($('mcp-args').value)});debugHistory.unshift({tool:t.name,result});debugHistory=debugHistory.slice(0,5);$('mcp-debug-result').textContent=JSON.stringify(debugHistory,null,2);await refreshApprovals();}catch(e){status(e.message);}};
$('approval-refresh').onclick=()=>refreshApprovals().catch(e=>status(e.message));
document.querySelector('[data-tab="mcp"]').addEventListener('click',()=>refreshApprovals().catch(e=>status(e.message)));
refreshMcp().catch(e=>status(e.message));refreshApprovals().catch(e=>status(e.message));api('/demo-orders').then(r=>{$('demo-orders').textContent=JSON.stringify(r.items,null,2);}).catch(e=>status(e.message));
