"""HA-0082 (A1): platform-owned plan for the payment_terms template.

Course: 生产级 Agent 排雷实战 L08 (plan-as-data). The plan is not generated by the
model and the model cannot change it: every step status is *projected* from
platform facts (blocks actually returned to the model, the verification state of
the latest submission, publication) each time something changes. Projection is a
pure function, so a later rejected submission moves S3 back to ``blocked`` and S4
becomes non-publishable again; it is not a one-way state machine.

``done`` for S1/S2 only means the platform's *literal-lexicon* candidates were
returned to the model; it does not mean all semantically relevant evidence was
found. ``partial`` never blocks S3: a partial business result is a legal outcome.
"""
from __future__ import annotations

PLAN_VERSION = 'dsh-plan@1'
STEPS = (
    ('S1', '定位付款相关证据块', ()),
    ('S2', '读取付款例外候选', ('S1',)),
    ('S3', '提交并通过结构化校验', ('S1',)),
    ('S4', '发布平台渲染结果', ('S3',)),
)


def _order(ids):
    return sorted(ids, key=lambda k: int(k.split('-')[1]))


def project(candidates, returned, review, published=False):
    """Return the plan as data. ``review`` carries submissions/accepted/last_codes."""
    payment, exception = candidates['payment'], candidates['exception']
    steps = []
    for step_id, title, depends in STEPS:
        step = {'step_id': step_id, 'title': title, 'depends_on': list(depends), 'evidence_ids': [],
                'missing_ids': [], 'error_codes': []}
        if step_id == 'S1':
            got = [k for k in payment if k in returned]
            step['evidence_ids'], step['missing_ids'] = got, [k for k in payment if k not in returned]
            step['status'] = ('not_applicable' if not payment else 'done' if not step['missing_ids']
                              else 'partial' if got else 'pending')
        elif step_id == 'S2':
            got = [k for k in exception if k in returned]
            step['evidence_ids'], step['missing_ids'] = got, [k for k in exception if k not in returned]
            step['status'] = ('not_applicable' if not exception else 'done' if not step['missing_ids']
                              else 'partial' if got else 'pending')
        elif step_id == 'S3':
            if review.get('accepted'):
                step['status'] = 'done'
            elif review.get('submissions'):
                step['status'], step['error_codes'] = 'blocked', list(review.get('last_codes') or [])
            else:
                step['status'] = 'pending'
        else:
            s3_done = review.get('accepted') is not None and review.get('accepted') is not False
            step['status'] = 'done' if published else 'ready' if s3_done else 'pending'
        steps.append(step)
    return {'version': PLAN_VERSION, 'template': 'payment_terms', 'steps': steps,
            'candidates': {'payment': _order(payment), 'exception': _order(exception)},
            'note': 'S1/S2 的 done 仅表示平台词表候选已返回给模型，不代表语义证据已找全。'}


def failed_step(plan):
    """First step that is neither done nor not_applicable; None if all are."""
    if not plan:
        return None
    for step in plan['steps']:
        if step['status'] not in ('done', 'not_applicable'):
            return step['step_id']
    return None


# Fixed platform error codes whose cause is a known step (jikesummary Replan下:
# the failure point is not the earliest unfinished step).
FAILURE_STEPS = {'DSH_FINDINGS_MISSING': 'S3', 'DSH_FINDINGS_INVALID': 'S3'}


def failure_point(plan, error_code):
    """Step the failure is attributed to: code mapping, then a blocked step, else earliest unfinished."""
    if not plan:
        return None
    if error_code in FAILURE_STEPS:
        return FAILURE_STEPS[error_code]
    blocked = next((s['step_id'] for s in plan['steps'] if s['status'] == 'blocked'), None)
    return blocked or failed_step(plan)


def summary(plan):
    """Compact, text-free line for the trusted state message."""
    return '；'.join(f"{s['step_id']} {s['title']}：{s['status']}"
                    + (f"（缺 {'、'.join(s['missing_ids'])}）" if s['missing_ids'] else '')
                    for s in plan['steps'])
